#pragma config(Sensor, S1,     color,          sensorCOLORFULL)
#pragma config(Motor,  motorA,          claw,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	waitForStart();
	motor[motorA] = 0;
	while(true) {
	  nxtDisplayTextLine(0, "");
	  nxtDisplayTextLine(1, "");
		getJoystickSettings(joystick);
		int lt = joystick.joy1_y2;
		int lx = joystick.joy1_x2;
		int lr = 0;
		int fb = 0;
		if (lt > 10) {
			fb = 1;
		}
		else if (lt < -10){
			fb = -1;
		}
		else {
			fb = 0;
		}

		if (lx > 10) {
			lr = 1;
		}
		else if (lx < -10) {
			lr = -1;
		}
		else {
			lr = 0;
		}

		if (fb == 1) {
			if (lr == 1)
			{
				motor[motorB] = 100;
				motor[motorC] = 100 - lx/1.27;
			}
			else if (lr == -1)
			{
				motor[motorC] = 100;
				motor[motorB] = 100 + lx/1.27;
			}
			else {
				motor[motorB] = 100;
				motor[motorC] = 100;
			}
		}
		else if (fb == -1){
			if (lr == 1)
			{
				motor[motorB] = -100;
				motor[motorC] = -100 + lx/1.27;
			}
			else if (lr == -1)
			{
				motor[motorC] = -100;
				motor[motorB] = -100 - lx/1.27;
			}
			else {
				motor[motorB] = -100;
				motor[motorC] = -100;
			}
		}
		else if (lr == -1) {
			motor[motorB] = -100;
			motor[motorC] = 100;
		}
		else if (lr == 1) {
			motor[motorB] = 100;
			motor[motorC] = -100;
		}
		else {
			motor[motorB] = 0;
			motor[motorC] = 0;
			nxtDisplayTextLine(0, "Motor B: %d",motorPWMLevel[motorB]);
			nxtDisplayTextLine(1, "Motor C: %d",motorPWMLevel[motorC]);
		}

		if (joystick.joy1_TopHat == 0) {
			motor[motorA] = 50;
		}
		else if (joystick.joy1_TopHat == 4) {
			motor[motorA] = -50;
		}
		else {
			motor[motorA] = 0;
		}
	}

}
